version: '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - API_URL=http://localhost:3000

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    environment:
      - PORT=3000 