FROM node:20-alpine as builder

WORKDIR /app

COPY package*.json ./

RUN npm install -g @angular/cli@17

RUN npm install

COPY . .

RUN ng build --configuration=production

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist/weather-forecast/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"] 